# Generated by Django 6.0.2 on 2026-02-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый')], default=1, verbose_name='Уровень сложности')),
                ('main_definition', models.TextField(verbose_name='Основное определение')),
                ('simple_explanation', models.TextField(verbose_name='Простое объяснение')),
                ('examples', models.TextField(blank=True, verbose_name='Примеры')),
                ('analogies', models.TextField(blank=True, verbose_name='Аналогии')),
                ('key_concepts', models.TextField(blank=True, verbose_name='Ключевые концепции')),
                ('common_mistakes', models.TextField(blank=True, verbose_name='Частые ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_question', models.TextField(verbose_name='Вопрос студента')),
                ('ai_response', models.TextField(verbose_name='Ответ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_cards', models.ManyToManyField(blank=True, to='ai_assistant.knowledgecard')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.IntegerField(choices=[(1, 'Не изучено'), (2, 'В процессе'), (3, 'Изучено'), (4, 'Освоено')], default=1, verbose_name='Уровень освоения')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('knowledge_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.knowledgecard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'knowledge_card')},
            },
        ),
    ]
