# Generated by Django 6.0.2 on 2026-02-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
