# Generated by Django 6.0.2 on 2026-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_userprofile_correct_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True, verbose_name='Уровень ранга')),
                ('name', models.CharField(max_length=50, verbose_name='Название ранга')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи ранга')),
                ('min_points', models.IntegerField(verbose_name='Минимум очков')),
                ('max_points', models.IntegerField(blank=True, null=True, verbose_name='Максимум очков')),
                ('color', models.CharField(choices=[('primary', 'Синий (IRON)'), ('success', 'Зеленый (BRONZE)'), ('info', 'Голубой (SILVER)'), ('warning', 'Оранжевый (GOLD)'), ('danger', 'Красный (PLATINUM)'), ('purple', 'Фиолетовый (DIAMOND)'), ('dark', 'Темный (MASTER)'), ('gold', 'Золотой (GRANDMASTER)')], default='primary', max_length=20, verbose_name='Цвет рамки')),
                ('description', models.TextField(blank=True, verbose_name='Описание ранга')),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
                'ordering': ['level'],
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='correct_answers',
            field=models.IntegerField(default=0, verbose_name='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wrong_answers',
            field=models.IntegerField(default=0, verbose_name='Неправильные ответы'),
        ),
    ]
