# Generated by Django 6.0.2 on 2026-02-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_rank_alter_userprofile_options_and_more'),
        ('schedule', '0004_schedulenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Очки по предмету')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильные ответы')),
                ('wrong_answers', models.IntegerField(default=0, verbose_name='Неправильные ответы')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='ai_assistant.userprofile')),
            ],
            options={
                'verbose_name': 'Рейтинг по предмету',
                'verbose_name_plural': 'Рейтинги по предметам',
                'ordering': ['-points'],
                'unique_together': {('user_profile', 'subject')},
            },
        ),
    ]
