# Generated by Django 6.0.2 on 2026-02-26 16:14

from django.db import migrations


def create_initial_task_categories(apps, schema_editor):
    """Создание начальных категорий задач"""
    TaskCategory = apps.get_model('ai_assistant', 'TaskCategory')
    
    categories = [
        {
            'name': 'Учеба',
            'color': '#4CAF50',
            'icon': 'fas fa-graduation-cap',
            'description': 'Задачи связанные с учебой и посещением занятий'
        },
        {
            'name': 'Работа',
            'color': '#2196F3',
            'icon': 'fas fa-briefcase',
            'description': 'Рабочие задачи и проекты'
        },
        {
            'name': 'Хобби',
            'color': '#FF9800',
            'icon': 'fas fa-palette',
            'description': 'Увлечения и развлекательные активности'
        },
        {
            'name': 'Спорт',
            'color': '#F44336',
            'icon': 'fas fa-running',
            'description': 'Физические упражнения и тренировки'
        },
        {
            'name': 'Семья',
            'color': '#E91E63',
            'icon': 'fas fa-home',
            'description': 'Семейные дела и обязанности'
        },
        {
            'name': 'Личное развитие',
            'color': '#9C27B0',
            'icon': 'fas fa-user-graduate',
            'description': 'Саморазвитие и обучение'
        },
        {
            'name': 'Здоровье',
            'color': '#00BCD4',
            'icon': 'fas fa-heartbeat',
            'description': 'Забота о здоровье и медицинские процедуры'
        },
        {
            'name': 'Покупки',
            'color': '#795548',
            'icon': 'fas fa-shopping-cart',
            'description': 'Планирование покупок и походы по магазинам'
        }
    ]
    
    for category_data in categories:
        TaskCategory.objects.get_or_create(
            name=category_data['name'],
            defaults=category_data
        )


def reverse_initial_task_categories(apps, schema_editor):
    """Удаление начальных категорий задач"""
    TaskCategory = apps.get_model('ai_assistant', 'TaskCategory')
    
    category_names = [
        'Учеба', 'Работа', 'Хобби', 'Спорт', 'Семья',
        'Личное развитие', 'Здоровье', 'Покупки'
    ]
    
    TaskCategory.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_taskcategory_tasktracker'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_task_categories,
            reverse_initial_task_categories
        ),
    ]
