# Generated by Django 6.0.2 on 2026-02-26 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_create_initial_task_categories'),
        ('schedule', '0004_schedulenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание заметки')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('category', models.CharField(choices=[('general', 'Общее'), ('homework', 'Домашнее задание'), ('exam', 'Экзамен'), ('project', 'Проект'), ('idea', 'Идея'), ('reminder', 'Напоминание')], default='general', max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('tags', models.CharField(blank=True, help_text='Введите теги через запятую', max_length=500, verbose_name='Теги')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.subject', verbose_name='Предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка студента',
                'verbose_name_plural': 'Заметки студентов',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
