# Generated by Django 6.0.2 on 2026-02-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_pointsadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Нормальный'), ('hard', 'Сложный')], max_length=10, verbose_name='Сложность бота')),
                ('result', models.CharField(choices=[('white_win', 'Победа белых'), ('black_win', 'Победа черных'), ('draw', 'Ничья'), ('playing', 'Игра идет'), ('abandoned', 'Брошена')], default='playing', max_length=20, verbose_name='Результат')),
                ('user_color', models.CharField(choices=[('white', 'Белые'), ('black', 'Черные')], default='white', max_length=5, verbose_name='Цвет пользователя')),
                ('fen_position', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', verbose_name='Позиция FEN')),
                ('moves_history', models.TextField(blank=True, verbose_name='История ходов')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало партии')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец партии')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Заработанные очки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шахматная партия',
                'verbose_name_plural': 'Шахматные партии',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChessStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0, verbose_name='Сыграно партий')),
                ('games_won', models.IntegerField(default=0, verbose_name='Побед')),
                ('games_drawn', models.IntegerField(default=0, verbose_name='Ничьих')),
                ('games_lost', models.IntegerField(default=0, verbose_name='Поражений')),
                ('easy_wins', models.IntegerField(default=0, verbose_name='Побед над легкими')),
                ('medium_wins', models.IntegerField(default=0, verbose_name='Побед над нормальными')),
                ('hard_wins', models.IntegerField(default=0, verbose_name='Побед над сложными')),
                ('chess_points', models.IntegerField(default=0, verbose_name='Очков в шахматах')),
                ('fastest_win', models.DurationField(blank=True, null=True, verbose_name='Самая быстрая победа')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Текущая серия побед')),
                ('best_streak', models.IntegerField(default=0, verbose_name='Лучшая серия побед')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шахматная статистика',
                'verbose_name_plural': 'Шахматная статистика',
            },
        ),
    ]
