# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0012_post_polloption_comment_pollvote_postlike'),
        ('schedule', '0004_schedulenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.personalscheduleitem', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выполнение задачи',
                'verbose_name_plural': 'Выполнения задач',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'schedule_item')},
            },
        ),
    ]
