# Generated by Django 6.0.2 on 2026-02-27 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0013_taskcompletion'),
        ('schedule', '0004_schedulenote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='class_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.classschedule', verbose_name='Занятие из расписания'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.personalscheduleitem', verbose_name='Персональная задача'),
        ),
        migrations.AddConstraint(
            model_name='taskcompletion',
            constraint=models.UniqueConstraint(fields=('user', 'schedule_item'), name='unique_user_schedule_item'),
        ),
        migrations.AddConstraint(
            model_name='taskcompletion',
            constraint=models.UniqueConstraint(fields=('user', 'class_schedule'), name='unique_user_class_schedule'),
        ),
    ]
