# Generated by Django 6.0.2 on 2026-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0014_alter_taskcompletion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
    ]
