# Generated by Django 6.0.2 on 2026-02-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('schedule', '0002_studentgroup_alter_classschedule_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='Включить уведомления')),
                ('notification_before_minutes', models.IntegerField(default=10, help_text='За сколько минут до начала пары отправлять уведомление', verbose_name='Уведомлять за N минут до пары')),
                ('late_threshold_minutes', models.IntegerField(default=5, help_text='Если студент не пришел через N минут после начала пары, считать опозданием', verbose_name='Порог опоздания (минуты)')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('class_start', 'Начало пары'), ('class_end', 'Конец пары'), ('late_student', 'Опоздание студента')], max_length=20, verbose_name='Тип уведомления')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classschedule', verbose_name='Расписание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Отправленное уведомление',
                'verbose_name_plural': 'Отправленные уведомления',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='LateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_at', models.DateTimeField(auto_now_add=True, verbose_name='Время опоздания')),
                ('notified', models.BooleanField(default=False, verbose_name='Уведомлено')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classschedule', verbose_name='Расписание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Опоздание',
                'verbose_name_plural': 'Опоздания',
                'ordering': ['-late_at'],
                'unique_together': {('student', 'schedule', 'late_at')},
            },
        ),
    ]
